apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: himanshu369/webapp:v1.0.4
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  type: LoadBalancer  # Creates an external LoadBalancer
  selector:
    app: web-app
  ports:
  - protocol: TCP
    port: 80      # Exposed service port
    targetPort: 80 # Container port

